apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app-deployment  # Cambiado el nombre a "to-do-app"
  namespace: group5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: to-do-app  # Cambiado el nombre a "to-do-app"
  template:
    metadata:
      labels:
        app: to-do-app  # Cambiado el nombre a "to-do-app"
    spec:
      containers:
        - name: to-do-container  # Cambiado el nombre a "to-do-container"
          image: sebasab/bootcamp_devops:latest  # Cambiada la imagen a "sebasab/bootcamp_devops"
          ports:
            - containerPort: 3000