apiVersion: v1
kind: Service
metadata:
  name: to-do-app-service
  namespace: group5  # Se ha añadido el campo "namespace"
spec:
  selector:
    app: to-do-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
