name: CI/CD for AWS EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sebasab
          password: Jpasa214Docker

      - name: Build and push Docker image
        run: |
          # Build and push your Docker image here
          docker build -t sebasab/bootcamp_devops:latest .
          docker push sebasab/bootcamp_devops:latest

